jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # STOP JS 20 error here
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4 # Or latest v5/v6
        with:
          path: kernel/source

      - name: Auto-Patch & Overclock
        run: |
          cd kernel/source
          # Auto-apply SUSFS 5.10
          git apply ../../50_add_susfs_in_gki-android12-5.10.patch
          # Force 2.4GHz Speed
          sed -i 's/2208000/2400000/g' arch/arm64/boot/dts/vendor/qcom/parrot-cpu.dtsi

      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: ./kernel/source/ # Local path for patched code
          config: Genevn.config 
          # Ensure Hybrid Mount engine is ON
          extra-cmd: scripts/config --file arch/arm64/configs/Genevn.config -e CONFIG_OVERLAY_FS
          
